version: "2"
services:
  patron-web:
    container_name: patron-web
    build: ./
    environment:
      CONFIG_FILE: /config/cm_libraries.txt
      NODE_ENV: production
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
