# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test, publish

on:
  # will run whenever commits are pushed to master or beta (such as a PR merge).
  push:
    branches: [master, beta]
  # will run on all PRs that are opened or updated (synchronized).
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Cache and install node modules
      uses: bahmutov/npm-install@v1
    - name: Lint
      run: npm run lint
      
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Cache and install node modules
      uses: bahmutov/npm-install@v1
    - name: Typecheck
      run: tsc --no-emit
      
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Cache and install node modules
      uses: bahmutov/npm-install@v1
    - name: Test
      run: npm run test
    
