# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build, test, publish

on:
  # will run whenever commits are pushed to master or beta (such as a PR merge).
  push:
    branches: [master, beta]
  # will run on all PRs that are opened or updated (synchronized).
  pull_request:
    types: [opened, synchronize]

jobs:
  install:
    name: Install Deps
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - run: npm run lint

