# This workflow will
#   - PRs and pushes to master/beta
#     - Install deps
#     - Lint
#     - Typecheck
#     - Test
#   - When PR Closed
#     - if on beta, publish as beta to docker hub
#     - if on master, create release with the contents of PR, we
#       will upload that image in a separate workflow when the release is created.
name: CI

on:
  # will run on all PRs that are opened or updated (synchronized)
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Cache and install node modules
      uses: bahmutov/npm-install@v1
    - name: Lint
      run: npm run lint
      
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Cache and install node modules
      uses: bahmutov/npm-install@v1
    - name: Typecheck
      run: tsc --noEmit
      
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Cache and install node modules
      uses: bahmutov/npm-install@v1
    - name: Test
      run: npm run test
          
  releaseMaster:
    name: Tag and Release master
    # only tag and release if this is a pull request being closed from 
    # a merge event on the master branch
    if: |
      github.base_ref == 'master' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merge == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # the tag will match the package.json version (eg. v1.0.0)
      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          strategy: package
          prefix: v
      - name: Release
        id: create_release
        if: steps.autotagger.outputs.tagname != ''
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.autotagger.outputs.tagname }}
          release_name: Version ${{ steps.autotagger.outputs.version }}
          # use the body of the PR as the release body
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
                    
  publishBeta:
    name: Publish beta image to Docker Hub
    # only publish if this is a pull request being closed from 
    # a merge event on the beta branch
    if: |
      github.base_ref == 'beta' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merge == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        id: publish_docker_hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kristojorgenson/patronweb
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
