# This workflow will publish the beta image to docker hub
name: Publish beta

# action will only run when a pull request to the beta branch is closed.
on:
  pull_request:
    branches: [ beta ]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_beta:
    name: Publish beta image to Docker Hub
    # only run if the PR is merged.
    if: github.event.pull_request.merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        id: publish_docker_hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kristojorgenson/patronweb
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
