# This workflow takes releases and publishes them to Docker Hub
name: Publish Master

# runs whenever a release is published (ie, it's created and is not a draft)
on:
  release:
    types: [created, published]

jobs:     
  publish_master:
    name: Publish master image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kristojorgenson/patronweb
          tag_with_ref: true
          add_git_labels: true
