# This workflow takes releases and publishes them to Docker Hub
name: Publish

# runs whenever a release is published (ie, it's created and is not a draft)
on:
  release:
    type: [created, published]

jobs:
  publish:
    name: Build Image and Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish to Docker Hub
      id: publish_docker_hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: myorg/myrepository
        tag_with_ref: true
